export type ZLifeModuleStatus = "active" | "development";

export type ZLifeModuleDefinition = {
  slug: string;
  name: string;
  shortName: string;
  icon: string;
  description: string;
  status: ZLifeModuleStatus;
  summary: string;
  capabilities: string[];
  launchHref?: string;
  nestedLabel?: string;
};

export const zlifeModules: ZLifeModuleDefinition[] = [
  { slug: "business", name: "Z-Life Business", shortName: "Business", icon: "▣", description: "Your all-in-one business command center.", status: "active", summary: "Run day-to-day business operations inside one connected workspace. Tree Service is the first active business vertical and establishes the reusable module pattern for future industries.", capabilities: ["Leads, customers, properties, estimates, scheduling, crews, jobs, invoices, and growth workflows", "Shared account, permissions, audit history, and provider boundaries", "Tree Service as the first active vertical inside the same Z-Life platform architecture"], launchHref: "/operate", nestedLabel: "Tree Service · Active module" },
  { slug: "assistant", name: "Z-Life AI Assistant", shortName: "AI Assistant", icon: "◎", description: "Your always-on AI teammate for life and business.", status: "active", summary: "A central guide that prioritizes work, connects users to the right module, and prepares the next useful action without silently performing high-impact actions.", capabilities: ["Daily priorities across active Z-Life modules", "Links directly into the workflow that needs attention", "Sensitive actions remain approval-gated"], launchHref: "/operate/assistant" },
  { slug: "web-builder", name: "Z-Life AI Web Builder", shortName: "AI Web Builder", icon: "▤", description: "Build, improve, and manage websites with AI.", status: "development", summary: "Create or connect websites, review suggested improvements, manage versions, and move changes through safe preview and release workflows.", capabilities: ["Website creation and connection", "AI-assisted improvement and change planning", "GitHub, preview, QA, and release controls"], launchHref: "/projects" },
  { slug: "app-builder", name: "Z-Life AI App Builder", shortName: "AI App Builder", icon: "⌘", description: "Turn an idea into working software with AI.", status: "development", summary: "Plan, generate, test, preview, and iterate on applications while preserving source control and release gates.", capabilities: ["Idea-to-plan workflows", "Source-controlled application builds", "Testing, preview, and exact-change release controls"], launchHref: "/projects" },
  { slug: "home", name: "Z-Life Home & Family", shortName: "Home & Family", icon: "⌂", description: "A smarter, simpler home and family life.", status: "development", summary: "A shared home-and-family workspace for household tasks, reminders, recurring maintenance, projects, schedules, records, and the information people choose to manage together. The first working slice now covers tasks and home-maintenance memory.", capabilities: ["Household tasks, priorities, due dates, and completion tracking", "Recurring home-maintenance items, cadence, location, and next-due tracking", "Shared workspace boundaries ready for family schedules, records, reminders, and cross-module connections"], launchHref: "/home", nestedLabel: "Working foundation · Tasks + maintenance" },
  { slug: "money", name: "Z-Life Money", shortName: "Money", icon: "$", description: "Clarity for today. Freedom for tomorrow.", status: "development", summary: "A future financial-organization module focused on costs, plans, and money workflows with explicit approval boundaries.", capabilities: ["Cost and budget visibility", "Connected financial organization where authorized", "Clear approval boundaries for paid or financial actions"] },
  { slug: "auto", name: "Z-Life Auto", shortName: "Auto", icon: "◇", description: "Everything for the road ahead.", status: "development", summary: "A future vehicle-management module for maintenance, documents, service history, costs, and reminders.", capabilities: ["Vehicle records and maintenance history", "Service and reminder tracking", "Cost visibility and documentation"] },
  { slug: "documents", name: "Z-Life Documents", shortName: "Documents", icon: "▱", description: "Find it. Use it. Keep it safe.", status: "development", summary: "A future document organization layer for locating, categorizing, and safely connecting important files across Z-Life.", capabilities: ["Searchable document organization", "Permission-aware access", "Workflow-to-document connections"] },
  { slug: "health", name: "Z-Life Health", shortName: "Health", icon: "♡", description: "A healthier, happier you.", status: "development", summary: "A future health and wellness organization module for information and routines users explicitly choose to connect.", capabilities: ["Personal wellness organization", "Connected records where explicitly authorized", "Clear privacy and permission boundaries"] },
  { slug: "travel", name: "Z-Life Travel", shortName: "Travel", icon: "✈", description: "Plan more. Experience more.", status: "development", summary: "A future trip-planning module for itineraries, reservations, documents, tasks, and shared travel details.", capabilities: ["Trip and itinerary organization", "Reservation and document references", "Shared planning with explicit permissions"] },
  { slug: "learning", name: "Z-Life Learning", shortName: "Learning", icon: "⌑", description: "Feed your curiosity. Build your future.", status: "development", summary: "A future learning workspace for goals, study plans, saved resources, and progress tracking.", capabilities: ["Learning goals and plans", "Saved resources", "Progress organization"] },
  { slug: "services", name: "Z-Life Services", shortName: "Services", icon: "⌁", description: "Find. Book. Get things done.", status: "development", summary: "A future service-discovery and booking layer designed to connect trusted service workflows into the larger Z-Life platform.", capabilities: ["Service discovery", "Request and booking workflows", "Connections to business modules and records"] }
];

export const zlifeModuleBySlug = new Map(zlifeModules.map((module) => [module.slug, module]));
